import { useState, useRef, useEffect } from 'react'
import { Upload, Image as ImageIcon, X, Loader2, Check, RefreshCw } from 'lucide-react'
import { supabase } from '@/lib/supabase'
import { toast } from 'sonner'
import ImagePicker from './ImagePicker'

const BUCKET = 'site-images'

// Local images that are available in public/images/ (generated by swap-images.mjs)
// The base path is hardcoded since we need absolute URLs for the img src
const BASE_PATH = '/crumbs-bakery-/images/'

const LOCAL_IMAGE_CATEGORIES = [
  {
    label: 'Fresh Bakes (decorative)',
    images: [
      'fresh-bakes-1.jpeg', 'fresh-bakes-2.jpeg', 'fresh-bakes-3.jpeg', 'fresh-bakes-4.jpeg',
    ],
  },
  {
    label: 'Menu Flatlays',
    images: [
      'cakes-menu.jpeg', 'cheesecake-menu.jpeg', 'fruit-cake-menu.jpeg',
    ],
  },
  {
    label: 'Cakes',
    images: [
      'japanese-cheesecake.jpeg', 'red-velvet-cake.jpeg', 'chocolate-cake.jpeg',
      'lemon-drizzle.jpeg', 'funfetti-sheet.jpeg', 'raspberry-ripple.jpeg',
      'carrot-cake-slice.jpeg', 'blueberry-cheesecake.jpeg', 'ny-cheesecake.jpeg',
    ],
  },
  {
    label: 'Cupcakes & Muffins',
    images: [
      'vanilla-cupcake.jpeg', 'chocolate-cupcake.jpeg', 'red-velvet-cupcake.jpeg',
      'lemon-curd-cupcake.jpeg', 'edible-photo-cupcake.jpeg', 'banana-choc-muffin.jpeg',
      'lemon-blueberry-muffin.jpeg',
    ],
  },
  {
    label: 'Cookies & Brownies',
    images: [
      'choc-chip-cookie.jpeg', 'brownies.jpeg', 'brownies-2.jpeg',
    ],
  },
  {
    label: 'Savory & Choux',
    images: [
      'chicken-pizza.jpeg', 'quiche.jpeg', 'chicken-pot-pies.jpeg',
      'cream-puffs.jpeg', 'eclair.jpeg',
    ],
  },
  {
    label: 'Other',
    images: [
      'delivery-bakery.jpeg', 'muffin.jpeg', 'french-macarons.jpeg',
      'tiramisu.jpeg', 'cinnamon-rolls.jpeg', 'banana-bread.jpeg',
      'bespoke-cake.jpeg', 'vintage-custom.jpeg', 'edible-photo-cake.jpeg',
    ],
  },
]

export default function ImageUploader({ value, onChange, label = 'Image', bucket = BUCKET }) {
  const [uploading, setUploading] = useState(false)
  const [pickerOpen, setPickerOpen] = useState(false)
  const [localPickerOpen, setLocalPickerOpen] = useState(false)
  const [previewError, setPreviewError] = useState(false)
  const [storageFiles, setStorageFiles] = useState([])
  const fileInputRef = useRef(null)

  // Load existing storage files when picker opens
  useEffect(() => {
    if (pickerOpen) {
      loadStorageFiles()
    }
  }, [pickerOpen])

  async function loadStorageFiles() {
    try {
      const { data, error } = await supabase.storage.from(bucket).list('', {
        limit: 100,
        sortBy: { column: 'created_at', order: 'desc' },
      })
      if (error) throw error
      setStorageFiles(data || [])
    } catch (err) {
      console.error('Failed to list storage files:', err)
      setStorageFiles([])
    }
  }

  async function handleFileUpload(e) {
    const file = e.target.files?.[0]
    if (!file) return
    await uploadFile(file)
    if (fileInputRef.current) fileInputRef.current.value = ''
  }

  async function uploadFile(file) {
    // Validate file type
    if (!file.type.startsWith('image/')) {
      toast.error('Please select an image file')
      return
    }
    // Validate size (max 10MB)
    if (file.size > 10 * 1024 * 1024) {
      toast.error('Image must be under 10MB')
      return
    }

    setUploading(true)
    try {
      // Generate unique filename
      const ext = file.name.split('.').pop() || 'jpeg'
      const filename = `${Date.now()}-${Math.random().toString(36).substring(2, 8)}.${ext}`
      
      const { data, error } = await supabase.storage
        .from(bucket)
        .upload(filename, file, {
          cacheControl: '3600',
          upsert: false,
        })
      
      if (error) throw error
      
      // Get public URL
      const { data: { publicUrl } } = supabase.storage
        .from(bucket)
        .getPublicUrl(data.path)
      
      onChange(publicUrl)
    } catch (err) {
      console.error('Upload failed:', err)
      toast.error('Upload failed. Make sure the site-images bucket exists in Supabase Storage.')
    } finally {
      setUploading(false)
    }
  }

  function handleSelectFromStorage(url) {
    onChange(url)
    setPickerOpen(false)
  }

  function handleSelectLocal(filename) {
    const url = `${BASE_PATH}${encodeURIComponent(filename)}`
    onChange(url)
    setLocalPickerOpen(false)
  }

  function handleRemove() {
    onChange('')
    setPreviewError(false)
  }

  return (
    <div>
      <label className="block text-xs font-medium text-gray-600 mb-1.5">{label}</label>

      {value ? (
        /* Image selected — show preview with controls */
        <div className="relative group">
          <img
            src={value}
            alt="Preview"
            className={`w-full h-32 object-cover rounded-lg border border-gray-200 ${previewError ? 'hidden' : ''}`}
            onError={() => setPreviewError(true)}
          />
          {previewError && (
            <div className="w-full h-32 rounded-lg border border-gray-200 bg-gray-50 flex items-center justify-center">
              <div className="text-center">
                <ImageIcon size={24} className="mx-auto text-gray-300 mb-1" />
                <p className="text-xs text-gray-400">Preview unavailable</p>
                <p className="text-[10px] text-gray-300 mt-1 break-all px-2">{value}</p>
              </div>
            </div>
          )}
          {/* Overlay controls */}
          <div className="absolute inset-0 bg-black/0 group-hover:bg-black/40 transition-colors rounded-lg flex items-center justify-center gap-2 opacity-0 group-hover:opacity-100">
            <button
              onClick={() => setPickerOpen(true)}
              className="p-1.5 bg-white rounded-full shadow hover:bg-gray-100 transition-colors"
              title="Choose from uploaded images"
            >
              <ImageIcon size={14} className="text-gray-700" />
            </button>
            <button
              onClick={() => setLocalPickerOpen(true)}
              className="p-1.5 bg-white rounded-full shadow hover:bg-gray-100 transition-colors"
              title="Choose from local images"
            >
              <RefreshCw size={14} className="text-gray-700" />
            </button>
            <button
              onClick={() => fileInputRef.current?.click()}
              className="p-1.5 bg-white rounded-full shadow hover:bg-gray-100 transition-colors"
              title="Upload new image"
            >
              <Upload size={14} className="text-gray-700" />
            </button>
            <button
              onClick={handleRemove}
              className="p-1.5 bg-white rounded-full shadow hover:bg-red-50 transition-colors"
              title="Remove image"
            >
              <X size={14} className="text-red-500" />
            </button>
          </div>
          <div className="absolute bottom-1 right-1">
            {uploading && <Loader2 size={14} className="animate-spin text-white drop-shadow" />}
          </div>
        </div>
      ) : (
        /* No image — show upload/pick actions */
        <div className="flex gap-2">
          <input
            ref={fileInputRef}
            type="file"
            accept="image/*"
            onChange={handleFileUpload}
            className="hidden"
          />
          <button
            onClick={() => fileInputRef.current?.click()}
            disabled={uploading}
            className="flex-1 border-2 border-dashed border-gray-300 rounded-lg px-4 py-6 text-center hover:border-teal-400 hover:bg-teal-50/30 transition-all disabled:opacity-50"
          >
            {uploading ? (
              <div className="flex items-center justify-center gap-2">
                <Loader2 size={16} className="animate-spin text-teal-500" />
                <span className="text-sm text-gray-500">Uploading...</span>
              </div>
            ) : (
              <div>
                <Upload size={20} className="mx-auto text-gray-400 mb-1" />
                <p className="text-xs text-gray-500">Click to upload</p>
                <p className="text-[10px] text-gray-400 mt-0.5">PNG, JPG up to 10MB</p>
              </div>
            )}
          </button>
          <button
            onClick={() => setPickerOpen(true)}
            className="px-3 py-2 border border-gray-200 rounded-lg text-xs text-gray-600 hover:bg-gray-50 hover:border-gray-300 transition-all shrink-0"
            title="Browse uploaded images"
          >
            Browse
          </button>
          <button
            onClick={() => setLocalPickerOpen(true)}
            className="px-3 py-2 border border-gray-200 rounded-lg text-xs text-gray-600 hover:bg-gray-50 hover:border-gray-300 transition-all shrink-0"
            title="Browse local images"
          >
            Local
          </button>
        </div>
      )}

      {/* Uploaded Images Picker Modal */}
      {pickerOpen && (
        <ImagePicker
          files={storageFiles}
          bucket={bucket}
          onSelect={handleSelectFromStorage}
          onUpload={uploadFile}
          onRefresh={loadStorageFiles}
          onClose={() => setPickerOpen(false)}
        />
      )}

      {/* Local Images Picker Modal */}
      {localPickerOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4">
          <div className="bg-white rounded-xl shadow-xl w-full max-w-2xl max-h-[85vh] flex flex-col">
            <div className="flex items-center justify-between px-5 py-4 border-b border-gray-100 shrink-0">
              <h2 className="font-semibold text-gray-900">Choose Local Image</h2>
              <button onClick={() => setLocalPickerOpen(false)} className="p-1 hover:bg-gray-100 rounded">
                <X size={16} />
              </button>
            </div>
            <div className="flex-1 overflow-y-auto p-5 space-y-6">
              {LOCAL_IMAGE_CATEGORIES.map((cat) => (
                <div key={cat.label}>
                  <h3 className="text-xs font-medium text-gray-500 uppercase tracking-wider mb-2">
                    {cat.label}
                  </h3>
                  <div className="grid grid-cols-4 sm:grid-cols-6 gap-3">
                    {cat.images.map((filename) => {
                      const url = `${BASE_PATH}${encodeURIComponent(filename)}`
                      const isSelected = value === url
                      return (
                        <button
                          key={filename}
                          onClick={() => handleSelectLocal(filename)}
                          className={`relative group rounded-lg overflow-hidden border-2 aspect-square transition-all ${
                            isSelected
                              ? 'border-teal-500 ring-2 ring-teal-200'
                              : 'border-gray-200 hover:border-teal-300 hover:shadow-md'
                          }`}
                        >
                          <img
                            src={url}
                            alt={filename}
                            className="w-full h-full object-cover"
                            onError={(e) => {
                              e.target.style.display = 'none'
                              e.target.parentElement.classList.add('bg-gray-100')
                              // Add text fallback
                              const span = document.createElement('span')
                              span.className = 'text-[8px] text-gray-400 p-1 text-center block'
                              span.textContent = filename
                              e.target.parentElement.appendChild(span)
                            }}
                          />
                          {isSelected && (
                            <div className="absolute top-1 right-1 bg-teal-500 rounded-full p-0.5">
                              <Check size={10} className="text-white" />
                            </div>
                          )}
                          <div className="absolute bottom-0 inset-x-0 bg-gradient-to-t from-black/60 to-transparent p-1 opacity-0 group-hover:opacity-100 transition-opacity">
                            <p className="text-[8px] text-white truncate">{filename}</p>
                          </div>
                        </button>
                      )
                    })}
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  )
}


